### ISSUE TITLE
Surface and mine levels do not match well

### ISSUE THREAD

**Issue by aligin** [andyleap/hnh-map#5]
Hello. I have a problem. When I firstly come into the mine the map is not matching correctly to the surface level. I tried to wipe all the data and start from scratch, but the problem is the same. I think the gap is one tile. See the picture.
![image](https://user-images.githubusercontent.com/6080294/78636926-0153c380-78b2-11ea-95b2-a6809a863c8c.png)

The version of auto-mapper is 4.10.
Amber Client v1.78.1

**Comment by andyleap** [comment]
You have to adjust the coordinates of the mine map.  Admins can do so by right clicking a tile and selecting "Rewrite tile coords for ....", Set the coords for the tile to the same as the matching surface tile, then they should be lined up correctly

**Comment by aligin** [comment]
Thanks, its working!
