### ISSUE TITLE
Can't see people when on a different map instance

### ISSUE THREAD

**Issue by K-marad** [andyleap/hnh-map#7]
For example, when you are on the surface, you can't see people in the mine.
And when you are offline you can't see anyone.

At my village we much preferred the v3 version, when you could see anyone that activated the navigation tracking whenever you'd like.
Like if someone types "help" on discord, I want to be able, even if not in hafen, to select his name in the jump to player list, and see that this person is on level 2 mine. And not have to check every different map instance to finally get to the place. 

Maybe it would be possible to toggle this with an option in the admin panel ? to have either the full rights to see everyone just like in v3, or to see only people on the same map instance as you like now.

**Comment by K-marad** [comment]
Also same with unkinned people of our own village, we would like to see their name, as we did in v3

**Comment by andyleap** [comment]
v4.14 should fix the unkinned people issue, the other issue sounds like they might not have navigation tracking working correctly?

**Comment by K-marad** [comment]
issue is actually a misconfiguration on the client side.
People not pressing enter after pasting the server url, so info not saved.
Thank you.
